### ISSUE TITLE
Integration of Flask server with GPS for movement

### ISSUE THREAD

**Issue by Blake2912** [Blake2912/Vahini-2.0#10]

**Comment by Blake2912** [comment]
#9

**Comment by amartyanambiar** [comment]
I'll do that right now. Give me 5 minutes.

**Comment by amartyanambiar** [comment]
check main branch. I have pushed it.

will have to do a test once to check if the code works. But as of now it looks good and sensible.

**Comment by Blake2912** [comment]
and one more thing don't push new changes to main branch

**Comment by Blake2912** [comment]
I have some clarifications... in the gps code which is receiving the gps coordinates will that run in background or should I specially call it somewhere to run it?

**Comment by Blake2912** [comment]
@amartyanambiar

**Comment by amartyanambiar** [comment]
> and one more thing don't push new changes to main branch 
> 

For every small thing i do a PR is unnecessary. Especially this sort of stuff. 
Which hardly affects any other code file... it's fine.

**Comment by Blake2912** [comment]
> > and one more thing don't push new changes to main branch
> 
> For every small thing i do a PR is unnecessary. Especially this sort of stuff. Which hardly affects any other code file... it's fine.

You don't need to do a PR just drop in the branch name I will pull it across from my end

**Comment by amartyanambiar** [comment]
> I have some clarifications... in the gps code which is receiving the gps coordinates will that run in background or should I specially call it somewhere to run it?
> 

I'm not sure. For now don't make it run in BG. We will have mem constraints too. So have to think over it.

But yes while movement it is reqd. To check if we r on the right path (as predicted)

**Comment by Blake2912** [comment]
> > I have some clarifications... in the gps code which is receiving the gps coordinates will that run in background or should I specially call it somewhere to run it?
> 
> I'm not sure. For now don't make it run in BG. We will have mem constraints too. So have to think over it.
> 
> But yes while movement it is reqd. To check if we r on the right path (as predicted)

Okay just check on the changes when I raise the PR

**Comment by amartyanambiar** [comment]
> > > and one more thing don't push new changes to main branch
> > 
> > 
> > For every small thing i do a PR is unnecessary. Especially this sort of stuff. Which hardly affects any other code file... it's fine.
> 
> You don't need to do a PR just drop in the branch name I will pull it across from my end

why bro why. the code is needed by both me and u.its standard why put in another branch again(unnecessary especially when only 1 person is working on that file) .

now delete all the comments by u and me which are not relevant to this issue. lets not make this DM.
in future this should serve as a Roadmap of ideas and decisions of 'why' we went ahead with 'what' .
@Blake2912

**Comment by amartyanambiar** [comment]
> > > > and one more thing don't push new changes to main branch
> > > 
> > > 
> > > For every small thing i do a PR is unnecessary. Especially this sort of stuff. Which hardly affects any other code file... it's fine.
> > 
> > 
> > You don't need to do a PR just drop in the branch name I will pull it across from my end
> 
> why bro why. the code is needed by both me and u.its standard why put in another branch again(unnecessary especially when only 1 person is working on that file) .
> 
> now delete all the comments by u and me which are not relevant to this issue. lets not make this DM. in future this should serve as a Roadmap of ideas and decisions of 'why' we went ahead with 'what' . @Blake2912

plus its not like i am just pushing to main only. check one PR is their for requiremnets.txt . check and merge. (bcos that required ur review).
