### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by amartyanambiar** [Blake2912/Vahini-2.0#11]
The plan is to create a separate module for drive functionalities.
That would involve transfer of functions relating to the movement(forward,reverse, automate) of the vehicle to separate package.

**Comment by amartyanambiar** [comment]
@Blake2912  why is the requirements.txt contain soo many packages? are we using the old senior's file?
if yes, we shall create a new one with the packages we use.
LMK and i'll work on it.

**Comment by Blake2912** [comment]
Go ahead if that's not a big work

**Comment by amartyanambiar** [comment]
Cool assigning myself.
Plus jus to clarify. currently we have used only those two libraries right..

**Comment by Blake2912** [comment]
Yeah but that is using tensor flow and stuff once check it by installing it in a separate env

**Comment by Blake2912** [comment]
And we are using flask also

**Comment by amartyanambiar** [comment]
will check that!

**Comment by amartyanambiar** [comment]
@Blake2912 pls check and lmk if i can merge the above. 
We shall close the issue once done.
