### ISSUE TITLE
Enhancement Required for the Web Interface for our flask server

### ISSUE THREAD

**Issue by Blake2912** [Blake2912/Vahini-2.0#18]
Create a more presentable interface by adding interactive buttons for easy usage and for easy understanding of the interface.

**Comment by amartyanambiar** [comment]
@healertrix created new branch for this issue.
```
git fetch origin
git checkout web-interface
git pull origin main
```
run this before working

**Comment by healertrix** [comment]
added assets and css for the interface will add functionalities in the next

**Comment by healertrix** [comment]
I have finalized the directional navigation page for our project. I think we should create a separate page for the add trees and save trees features and link them to the navigation bar. Please check the changes I made in the neointerface folder and let me know if you have any feedback or suggestions.

**Comment by amartyanambiar** [comment]
Add a PR also.
Yes you should put a separate page for trees.(thats better)

the interface, i checked. 
Everything looks better now! Can u try reducing the radiant purple radius..it looks too huge.

**Comment by amartyanambiar** [comment]
Add a PR. so that we can review the code properly.

**Comment by healertrix** [comment]
will make the changes you asked 
and will make a seperate page for the trees

**Comment by Blake2912** [comment]
Please do the following enhancements:
 - Removal of the toggle button
 - Adding and integration of the stop button (test it and see if you get a stop log in the flask log)
 - Integration of map module in the interface
@amartyanambiar you can add any points if required, and @healertrix please complete these asap

**Comment by healertrix** [comment]
ok
