### ISSUE TITLE
Addition of function to return the adjacent connected nodes for a given node

### ISSUE THREAD

**Issue by Blake2912** [Blake2912/Vahini-2.0#34]

**Comment by amartyanambiar** [comment]
much need to make the UI become intelligent.

**Comment by Blake2912** [comment]
Approach for solving this problem, creation of two API Routes 
1. `/fetch-all-nodes` a simple GET API which will return all the nodes in the graph
2. `/fetch-neighbours` a simple POST API which takes the `current_node` and returns neighbours

Frontend requirements would be to integrate the two apis
