### ISSUE TITLE
Integration and Code Refactor required in Vehicle Simulation module

### ISSUE THREAD

**Issue by Blake2912** [Blake2912/Vahini-2.0#45]
@amartyanambiar please take up this task and do the needful,

- [x] Refactor the code to create functions which can be called from any place
- [x] Adding of function if the water is low on the vehicle
- [x] Device an algorithmic flow for the simulation which can be presented on the review
- [x] If possible explore on how to integrate it with the present interface

You can make use of your test module for the same

**Comment by Blake2912** [comment]
@amartyanambiar is it required to address the last point or can we mark that as completed?

**Comment by amartyanambiar** [comment]
As of now, I am not looking forward to doing it.
