### ISSUE TITLE
Geocoding of Trees on the predefined path

### ISSUE THREAD

**Issue by Blake2912** [Blake2912/Vahini-2.0#8]
The goal is to use our present Web Interface to add trees to the existing Path.

**Comment by amartyanambiar** [comment]
I will start working on this. assign it to me

**Comment by Blake2912** [comment]
I have assigned it to everybody create a branch link it and start working on it

**Comment by Blake2912** [comment]
#9

**Comment by Blake2912** [comment]
sync the branch before you push the code
